name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x

    - name: npm install
      run: npm install

    - name: npm test
      run: npm test